<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Purchase Order {{ $purchaseOrder->po_number }}</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; margin: 0; padding: 20px; }
        .header { border-bottom: 2px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { margin: 0; color: #1e293b; font-size: 28px; }
        .header p { margin: 5px 0 0 0; color: #64748b; font-size: 14px; }
        .meta-table { width: 100%; margin-bottom: 30px; }
        .meta-table td { width: 50%; vertical-align: top; }
        .meta-label { font-weight: bold; color: #64748b; font-size: 12px; text-transform: uppercase; margin-bottom: 5px; }
        .meta-value { font-size: 16px; margin-bottom: 15px; }
        .items-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .items-table th { background: #f8fafc; text-align: left; padding: 12px; border-bottom: 2px solid #e2e8f0; font-size: 12px; color: #64748b; text-transform: uppercase; }
        .items-table td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
        .footer { text-align: center; color: #94a3b8; font-size: 12px; margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>PURCHASE ORDER</h1>
        <p>Document #: {{ $purchaseOrder->po_number }}</p>
    </div>

    <table class="meta-table">
        <tr>
            <td>
                <div class="meta-label">Order Date</div>
                <div class="meta-value">{{ $purchaseOrder->created_at->format('M d, Y - h:i A') }}</div>
                
                <div class="meta-label">Generated By</div>
                <div class="meta-value">{{ $purchaseOrder->creator->name ?? 'System' }}</div>
            </td>
            <td>
                <div class="meta-label">Status</div>
                <div class="meta-value" style="text-transform: uppercase; font-weight: bold; color: {{ $purchaseOrder->status == 'received' ? '#10b981' : '#f59e0b' }};">
                    {{ $purchaseOrder->status }}
                </div>
                
                @if($purchaseOrder->status == 'received')
                <div class="meta-label">Received Date</div>
                <div class="meta-value">{{ $purchaseOrder->received_at->format('M d, Y - h:i A') }}</div>
                @endif
            </td>
        </tr>
    </table>

    <table class="items-table">
        <thead>
            <tr>
                <th>Item / SKU</th>
                <th>Category</th>
                <th style="text-align: right;">Order Qty</th>
                <th style="text-align: right;">Unit Price</th>
                <th style="text-align: right;">Total Value</th>
            </tr>
        </thead>
        <tbody>
            @php $totalValue = 0; @endphp
            @foreach($purchaseOrder->items as $item)
            @php 
                $itemTotal = $item->quantity * ($item->product->price ?? 0);
                $totalValue += $itemTotal; 
            @endphp
            <tr>
                <td>
                    <strong>{{ $item->product->name ?? 'Unknown Product' }}</strong><br>
                    <span style="color: #64748b; font-size: 12px;">{{ $item->product->sku ?? 'N/A' }}</span>
                </td>
                <td>{{ $item->product->category->name ?? '-' }}</td>
                <td style="text-align: right; font-weight: bold;">{{ number_format($item->quantity) }}</td>
                <td style="text-align: right;">₹{{ number_format($item->product->price ?? 0, 2) }}</td>
                <td style="text-align: right;">₹{{ number_format($itemTotal, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" style="text-align: right; padding-top: 20px; font-weight: bold;">GRAND TOTAL:</td>
                <td style="text-align: right; padding-top: 20px; font-weight: bold; font-size: 18px;">₹{{ number_format($totalValue, 2) }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by StockFlow Warehouse Management System on {{ now()->format('M d, Y') }}
    </div>
</body>
</html>
